backend/audio/urls.py
from django.urls import path
from . import views



app_name = 'audio'
urlpatterns = [
    path('', views.dash, name='dash'),
    path('match-audio/<int:level>/<int:lesson>/<int:chunks>', views.match_audio, name='match-audio'),
]

backend/backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext as _
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
   path("admin/", admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += i18n_patterns ( 
    url('', include('homepage.urls', namespace='homepage')),
    url('user-dash', include('user_dash.urls', namespace='user-dash')),
    url('learn/', include('learn.urls', namespace='learn')),
    url('create/', include('create.urls', namespace='create')),
    url('audio/', include('audio.urls', namespace='audio')),
    path("reset-password-sent", auth_views.PasswordResetDoneView.as_view(template_name='password-reset-sent.html'), name='password_reset_done'),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='password-reset-form.html'), name='password_reset_confirm'),
    path("reset-password-complete", auth_views.PasswordResetCompleteView.as_view(template_name='password-reset-complete.html'), name='password_reset_complete'),
    
   

)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

backend/homepage/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'homepage'
urlpatterns = [
    path("", views.homepage, name='homepage'),
    path("login", views.login_form, name='login'),
    path('logout', views.logout_form, name='logout'),
    path("signup", views.signup_form, name='signup'),
    path("signup", views.signup_form, name='signup'),
    path("verify-email", views.verify_email, name='verify-email'),
    path("podcast", views.podcast, name='podcast'),
    path("sample", views.sample, name='sample'),
    path("reset-password", auth_views.PasswordResetView.as_view(template_name='reset-password.html'), name='reset_password'),
    

]

backend/learn/urls.py
from django.urls import path
from . import views


app_name = 'learn'
urlpatterns = [
    path('dash', views.dash, name='dash'),
    path('my-account/', views.my_account, name='my-account'),
    path('select-lesson/<int:level>', views.select_lesson, name='select-lesson'),
    path('lesson/<int:level>/<int:id>', views.lesson, name='lesson'),
    path('add-remove-homework/', views.add_remove_homework, name='add-remove-homework'),
    path('homework/', views.homework, name='homework'),
    path("check-username-exists/", views.ajax_check_username_exists, name='check-username-exists'),
    path('adjust-progress/', views.adjust_progress, name='adjust-progress'),
    path('no-cheating/', views.no_cheating, name='no-cheating'),
    

] 

backend/homepage/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from create.models import Level

class UserProfileManager(BaseUserManager):
    """ Manager for user profiles """
    def create_user(self, email, username, password=None,):
        """ Create a new user profile """
        if not email:
            raise ValueError('User must have an email address')

        email = self.normalize_email(email)
        user = self.model(email=email, username=username)
        

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, username, password):
        """ Create a new superuser profile """
        user = self.create_user(email,username, password)
        user.is_superuser = True
        user.is_staff = True

        user.save(using=self._db)

        return user


class UserProfile(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=255)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    homework_list = models.JSONField(default=list, blank=True, null=True)
    website_lang = models.CharField(max_length=255, default='')
    results = models.JSONField(default=dict, blank=True, null=True)
    progress = models.IntegerField(default=1)
    first_lang = models.CharField(max_length=10, default='')
    hw_first_lang = models.CharField(max_length=10, default='eng')
    verification_code = models.IntegerField(default=0)
 

    objects = UserProfileManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        # return string representation of user
        return self.email

    def adjust_user_results(request,level, lesson_id, score, lesson_len):
        user = UserProfile.objects.get(email=request.user)
        results_obj = user.results
        lesson_id = str(lesson_id)
        try:
            level_res = results_obj[level]
        except:
            level_res = None
        if level_res:
            level_obj = results_obj[level]
            try:
                lesson_res = level_obj[lesson_id]
            except:
                lesson_res = None
            if lesson_res:
                prev_top_score = level_obj[lesson_id]
                if score > prev_top_score[0]:
                    level_obj[lesson_id][0] = score
            else:
                level_obj[lesson_id] = [score, lesson_len]
        else:
            level_obj = { lesson_id: [score, lesson_len] }
            results_obj[level] = level_obj
        user.results = results_obj
        user.save()
        queryset = Level.objects.get(level=level)
        level_length = len(queryset.order)
        max_level = set_level_progress(level_obj, level, level_length)
        level_up = False
        if int(max_level) > user.progress:
            user.progress = max_level
            user.save()
            level_up = True
        return level_up, max_level
    
def set_level_progress(results, current_level, level_length):
    if len(results.keys()) == level_length:
        for i in results.values():
            if i[0] != i[1]:
                return current_level
        return int(current_level) + 1
    else:
        return current_level
            
        

    

        

backend/homepage/forms.py
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import UserProfile
from django import forms
from django.forms import CharField, EmailField, EmailInput, ModelChoiceField, PasswordInput, TextInput
from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate, gettext


class NewUserForm(UserCreationForm):
    
    class Meta:
        model = get_user_model()
        fields = ['email', 'username']
        
    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = EmailInput(attrs={'class': 'form-control', 'placeholder':  _('email')})
        self.fields['username'].widget = TextInput(attrs={'class': 'form-control', 'placeholder':  _('username')})
        self.fields['password1'].widget = PasswordInput(attrs={'class': 'form-control', 'placeholder':  _('password')})
        self.fields['password2'].widget = PasswordInput(attrs={'class': 'form-control', 'placeholder':  _('repeat password')})
        for fieldname in ['email','username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].label = ''

class UserAuthenticationForm(AuthenticationForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget = TextInput(attrs={'class': 'form-control', 'placeholder':  _('email')})
        self.fields['password'].widget = PasswordInput(attrs={'class': 'form-control', 'placeholder': _('password')})
        for fieldname in ['username','password']:
            self.fields[fieldname].label = ''
            


    def confirm_login_allowed(self, user):
        
        if not user.is_active or not user.is_validated:
            raise forms.ValidationError('There was a problem with your login.', code='invalid_login')

backend/homepage/views.py
from django.shortcuts import render, redirect
from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate, gettext
from .models import UserProfile
from .forms import NewUserForm, UserAuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.core.exceptions import ValidationError
from random import randrange
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
import os


def homepage(request):
    if request.user.is_authenticated:
        return redirect('learn:dash')
    #trans = translate(language='en')
    return render(request, 'homepage.html')

def sample(request):
    return render(request, 'sample.html')


def verify_email(request):
    msg = ''
    if request.POST:
        user_code = request.POST.get('code')
        user_model = UserProfile.objects.get(email=request.user)

        if user_code == str(user_model.verification_code):
            user_model.is_verified = True
            user_model.verification_code = 0
            user_model.save()
            return redirect('homepage:homepage')
        else:
            msg = 'incorrect code'
    context = {'msg': msg}
    return render(request, 'verify-email.html', context)


def login_form(request):
    if request.user.is_authenticated:
        return redirect('learn:dash')
    if request.method == 'GET':
        return render(request, 'login.html', {'form': UserAuthenticationForm()})
    else:
        user = authenticate(
            request, email=request.POST['username'], password=request.POST['password'])

        if user is None:
            return render(request, 'login.html', {'form': UserAuthenticationForm(), 'error': 'username or password incorrect'})
        else:
            login(request, user)
            if request.user.is_superuser:
                return redirect('homepage:homepage')
            else:
                return redirect('learn:dash')


def logout_form(request):
    if request.method == "POST":
        logout(request)
        return redirect('homepage:homepage')


def signup_form(request):
    if request.user.is_authenticated:
        return redirect('user_dash:index')
    if request.method == 'GET':
        return render(request, 'signup.html', {'form': NewUserForm()})
    else:
        # check if email is in focus group -------------------
        focus_string = str(os.getenv('FOCUS_GROUP'))
        focus_group = [x.strip() for x in focus_string.split(',')]
        if request.POST['email'] not in focus_group:
            msg = 'focus-group-error'
            return render(request, 'signup.html', {'form': NewUserForm(), 'error': msg})
        # end check ------------------------
        if request.POST['password1'] == request.POST['password2']:
            try:
                four_digit_code = randrange(1000, 9999)
                language_code = request.POST.get('language-code')
                user = UserProfile.objects.create_user(
                    request.POST['email'], request.POST['username'], password=request.POST['password1'])
                user.verification_code = four_digit_code
                user.website_lang = language_code
                user.save()

                subject = 'Verification Code'
                html_message = render_to_string(
                    'verification-mail-template.html', {'user': user.username, 'code': four_digit_code})
                plain_message = strip_tags(html_message)
                from_email = 'slolearner.net <contact@slolearner.net>'
                to = request.POST['email']
                mail.send_mail(subject, plain_message, from_email, [
                               to], html_message=html_message)
                login(request, user)
 
                return redirect('homepage:verify-email')
            except IntegrityError:
                ValidationError("User with this email already exist")
                return render(request, 'customer/auth/signup.html', {'form': NewUserForm(), 'error': 'account already exists under this email'})

        else:
            return render(request, 'customer/auth/signup.html', {'form': NewUserForm(), 'error': 'passwords did not match'})


def podcast(request):
    return render(request, 'podcast.html')


def translate(language, string):
    cur_language = get_language()
    try:
        activate(language)
        text = gettext(string)
    finally:
        activate(cur_language)
    return text

backend/homepage/templates/base.html
{% load i18n %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link rel="stylesheet" href="https://bootswatch.com/5/slate/bootstrap.min.css" />
    <link rel="stylesheet" href="{% static '/styles/base.css' %}" />
    <!-- <link rel="stylesheet" media="screen and (max-width: 1050px)" href="{% static '/styles/mobile.css' %}"/>-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.11.0/devicon.min.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    
    <!--<script src="{% static '/scripts/main.js' %}"></script> was casing MIME error. Is it needed?-->
    <title>slolearner.net</title>
    <link rel="icon" href="{% static 'images/tortoise.png' %}" type="image/x-icon">
    {% block css %} {% endblock %}
</head>

<body class="container unselectable">
    {% get_current_language as LANGUAGE_CODE %} {% get_available_languages as LANGUAGES %} {% get_language_info_list for LANGUAGES as languages %}
    <nav id="navbar" class="navbar border border-white navbar-expand-lg m-1">
        <div class="container">

            {% if user.is_authenticated %}
            <a class="slo-learner-banner m-1 text-decoration-none" href="{% url 'learn:dash' %}">
              <span class="text-danger">slo</span>
              <img src="{% static 'images/tortoise-white.png' %}" class="tortoise-white-png" >
              <span class="text-info">learner</span>
            </a>
            {% endif %} 
             
             
            
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav">
            {% for lang in languages %}
            
            <li class="nav-item">
              {% if request.path == "/en/" or request.path == "/sl/"  %}
              <a class="m-1" href="/{{ lang.code }}">
              {% if lang.name_local == 'English' %}
              <img src="{% static 'images/eng-flag.png' %}" class="flag-icon" >
              {% else %}
              <img src="{% static 'images/slo-flag.png' %}" class="flag-icon" >
              {% endif %}
            </a> {% elif request.path == "/en/user-dash" or request.path == "/sl/user-dash" %}
            
            <a href="/{{ lang.code }}/learn/dash">
                {{ lang.name_local }}
              </a> {% else %} 
              
              {% endif %}
            </li>
            {% endfor %}
             {% if user.is_authenticated %}
             {% if user.is_superuser %}
            <li class="nav-item">
                <a class="link"  href="{% url 'create:dash' %}">create </a>
            </li>
            
            {% endif %}
            <li class="nav-item"><a class="link"  href="{% url 'learn:dash' %}">{% translate "dashboard" %}</a></li>
            <li class="nav-item"><a class="link"  href="{% url 'learn:homework' %}">{% translate "homework" %}</a></li>
            <li class="nav-item"><a class="link"  href="{% url 'homepage:podcast' %}">{% translate "podcast" %}</a></li>
            <li class="nav-item"><a class="link"  href="{% url 'learn:my-account' %}">{% translate "my account" %}</a></li>
            <form action="{% url 'homepage:logout' %}" method="POST" class="log-out-form" >
              {% csrf_token %}
              <button type="submit" class=" btn btn-sm btn-danger" >
            Logout
          </button>
          </form>
            {% else %}
            <li class="nav-item">
              <a class="link" href="{% url 'homepage:homepage' %}">{% translate "home" %}</a>
             </li>
            
            <li class="nav-item">
                <a class="link" href="{% url 'homepage:login' %}">{% translate "login" %}</a>
            </li>
            <li class="nav-item">
                <a class="link" href="{% url 'homepage:signup' %}">{% translate "sign up" %}</a>
            </li>
            <li class="nav-item"><a class="link"  href="{% url 'homepage:podcast' %}">{% translate "podcast" %}</a></li>
            <li class="nav-item">
                <a class="link" href="{% url 'homepage:homepage' %}">{% translate "contact" %}</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <main > {% block content %} {% endblock %}</main>

    <footer>
    
            <span>slolearner.net &copy;</span>
            
            </footer>
</body>

</html>

backend/homepage/templates/homepage.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<link rel="stylesheet" href="{% static 'styles/homepage/landing-page.css' %}" /> {% endblock %}
<div class="landing-page-wrapper">
   
      <div class="slo-learner-banner">
        <span class="navbar-slo text-danger">slo</span>
        <img src="{% static 'images/tortoise-white.png' %}" class="tortoise-white-png" >
      <span class="navbar-learner text-info">learner</span></a>
      </div>
      
    <div class="border-top m-1 p-1 border-danger border-3">
      <h2>
        {% translate "LEARN SLOVENE ONLINE" %}
      </h2>
      
    </div>
    <div class="bullet-points border-top border-info border-2">
        <div class="bullet">
      <i class="fa-solid fa-laptop"></i>
      <p>{% translate "interactive learning" %}</p>
    </div>
    <div class="bullet">
      <i class="fa-solid fa-podcast"></i>
      <p>{% translate "accompanying podcast" %}</p>
    </div>
        <div class="bullet">
      <i class="fa-solid fa-layer-group"></i>
      <p>{% translate "level based progression" %}</p>
    </div>
        <div class="bullet">
        <i class="fa-solid fa-volume-high"></i>
      <p>{% translate "audio clips for pronunciation" %}</p>
    </div>
    </div>
    <div class="bullet-points"> 
        <div>
            <a class="btn btn-danger" href="{% url 'homepage:signup' %}">{% translate "sign up" %}</a>
            <a class="btn btn-light" href="{% url 'homepage:login' %}">{% translate "login" %}</a>
            <a class="btn btn-info" href="{% url 'homepage:sample' %}">{% translate "try out" %}</a>
        </div>
         
    </div>
</div>

{% endblock %}

backend/homepage/templates/login.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<!-- <link rel="stylesheet" href="{% static 'styles/homepage/styles.css' %}" />
<link rel="stylesheet" media="screen and (max-width: 1050px)" href="{% static 'styles/homepage/mobile.css' %}"/> -->
{% endblock %}

<div class="auth-form-wrapper">
<h3 class="border-top border-danger border-3">{% translate "login" %}</h3>
 {{ error }}
    <form class="auth-form border-top border-info border-2 p-2" method="POST">
      {% csrf_token %}
        <div class="auth-form-inputs">{{ form.as_p }}</div>
        <button type="submit" class="btn btn-info">{% translate "login" %}</button>
        <br>
        <br>
        <a  href="{% url 'homepage:signup' %}">{% translate "don't have an account?" %}</a>
        <br>
        <a  href="{% url 'homepage:reset_password' %}">{% translate "forgot password?" %}</a>
    </form>
</div>

{% endblock %}

backend/homepage/templates/password-reset-complete.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<!-- <link rel="stylesheet" href="{% static 'styles/homepage/styles.css' %}" />
<link rel="stylesheet" media="screen and (max-width: 1050px)" href="{% static 'styles/homepage/mobile.css' %}"/> -->
{% endblock %}

<h3>{% translate "email reset" %}</h3>

<a href="{% url 'homepage:login' %}">{% translate "log in" %}</a>

{% endblock %}

backend/homepage/templates/password-reset-form.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<!-- <link rel="stylesheet" href="{% static 'styles/homepage/styles.css' %}" />
<link rel="stylesheet" media="screen and (max-width: 1050px)" href="{% static 'styles/homepage/mobile.css' %}"/> -->
{% endblock %}

<h3>{% translate "enter new password" %}</h3>
<span id="error-msg" class="m-1 text-danger"></span>
    <form id="email-form" method="POST">
      {% csrf_token %}
      {{ form }}
      <br>
      <button type="submit" class="btn btn-primary m-1">{% translate "submit" %}</button>
    </form>
</div>

<input id="placeholder-text1" type="hidden" value="{% translate 'password' %}">
<input id="placeholder-text2" type="hidden" value="{% translate 'repeat password' %}">
<input id="path" type="hidden" value="{{ request.path }}">
<script>
  $('label[for="id_new_password1"]').hide()
  $('label[for="id_new_password2"]').hide()
  document.getElementsByClassName('helptext')[0].classList.add('d-none')
  const input1 = document.getElementById('id_new_password1')
  const input2 = document.getElementById('id_new_password2')

  input1.classList.add('form-control','m-2')
  input2.classList.add('form-control','m-2')

  input1.placeholder = document.getElementById('placeholder-text1').value
  input2.placeholder = document.getElementById('placeholder-text2').value

  // errors 
  const error = document.getElementsByClassName('errorlist')[0]
  error.classList.add('d-none')
  const msg = error.children[0].innerHTML
  const messages = {'The two password fields didn’t match.': 'Polji za geslo se nista ujemali.',
  'This password is too short. It must contain at least 8 characters.':'To geslo je prekratko. Vsebovati mora vsaj 8 znakov.',
  'This password is too common.':'To geslo je prepogosto.',
  'This password is entirely numeric.': 'To geslo je v celoti številčno.',
  'The password is too similar to the email.':'Geslo je preveč podobno e-naslov.',
  'The password is too similar to the username.': 'Geslo je preveč podobno uporabniškemu imenu.'}
  
  const path = document.getElementById('path')
  const lang = path.value.slice(0,3)
  if (lang == '/sl'){
    document.getElementById('error-msg').innerHTML = messages[msg]
  } else {
    document.getElementById('error-msg').innerHTML = msg
  }
  
</script>
{% endblock %}

backend/homepage/templates/password-reset-sent.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<!-- <link rel="stylesheet" href="{% static 'styles/homepage/styles.css' %}" />
<link rel="stylesheet" media="screen and (max-width: 1050px)" href="{% static 'styles/homepage/mobile.css' %}"/> -->
{% endblock %}

<h3>{% translate "email sent" %}</h3>
<p>{% translate "please check your email and click the link provided" %}</p>


{% endblock %}

backend/homepage/templates/podcast.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<link rel="stylesheet" href="{% static 'styles/learn/dash.css' %}" /> {% endblock %}

<h3>THE</h3>
<div class="slo-learner-podcast-banner">
    <span class="text-danger">slo</span>
    <img src="{% static 'images/tortoise-white.png' %}" class="tortoise-white-png" />
    <span class="navbar-learner text-info">learner</span>
</div>

<h3>PODCAST</h3>
<img src="{% static 'images/coming-soon.png' %}">
{% endblock %}

backend/homepage/templates/reset-password.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<!-- <link rel="stylesheet" href="{% static 'styles/homepage/styles.css' %}" />
<link rel="stylesheet" media="screen and (max-width: 1050px)" href="{% static 'styles/homepage/mobile.css' %}"/> -->
{% endblock %}

 
<h3>{% translate "password reset" %}</h3>
    <form id="email-form" method="POST">
      {% csrf_token %}
      {{ form }}
      <br>
      <button class="btn btn-primary m-1" onclick="onSubmit()">{% translate "send email" %}</button>
    </form>
     
      <div id="spinner" class="spinner-border text-info invisible" role="status"></div>

      <input id="placeholder-text" type="hidden" value="{% translate 'email' %}">
<script>
  $('label[for="id_email"]').hide()
  

  const input = document.getElementById('id_email')
  input.placeholder = document.getElementById('placeholder-text').value
  input.classList.add('form-control','m-2')

  function onSubmit(){
    document.getElementById('spinner').classList.remove('invisible')
    document.getElementById('email-form').classList.add('d-none')
  }
</script>
{% endblock %}

backend/homepage/templates/signup.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<!-- <link rel="stylesheet" href="{% static 'styles/homepage/styles.css' %}" />
<link rel="stylesheet" media="screen and (max-width: 1050px)" href="{% static 'styles/homepage/mobile.css' %}"/> -->
{% endblock %}
{% get_current_language as LANGUAGE_CODE %}
<div class="auth-form-wrapper">
    <h3 class="border-top border-danger border-3">{% translate "create an account" %}</h3>
    <form class="auth-form border-top border-info border-2 p-2" method="POST" name="form" id="form">
        {% if error == 'focus-group-error' %}
        <div class="border border-3 border-danger rounded p-2 m-2">{% translate "Account creation is currently closed for new users, apologies. Please check back later" %}</div>
        {% else %}
        <br>
        {% endif %}
      {% csrf_token %}
        <div class="auth-form-inputs">
            {{ form.as_p }}
        </div>
 
        
        <button type="submit" class="btn btn-info" onclick="showSpinner()">{% translate "sign up" %}</button>
        <br>
        <br>
        <a  href="{% url 'homepage:login' %}">{% translate "already have an account?" %}</a>
        <input type="hidden" name="language-code" value={{ LANGUAGE_CODE }}>
    </form>
    <div id="spinner" class="invisible border-top border-info">
        <h5>{% translate "please wait..." %}</h5>
        <br>
        <div class="spinner-border text-info" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
</div>

<script>
    function showSpinner(){
        const form = document.getElementById('form')
        const spinner = document.getElementById('spinner')
        form.classList.add('d-none')
        spinner.classList.remove('invisible')
        

    }
</script>
{% endblock %}

backend/homepage/templates/verification-mail-template.html
<h1>hello {{ user }}</h1>

<span>your code is <h3>{{ code }}</h3></span>

backend/homepage/templates/verify-email.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<!-- <link rel="stylesheet" href="{% static 'styles/homepage/styles.css' %}" />
<link rel="stylesheet" media="screen and (max-width: 1050px)" href="{% static 'styles/homepage/mobile.css' %}"/> -->
{% endblock %}


<div class="mt-5">
    <h3>{% translate "email sent" %} to <span class="text-info">{{ user }}</span></h3>
    <span class="text-danger">{{ msg }}</span>
    <form method="POST" class="m-2 p-2">
        {% csrf_token %}
        <input type="text" name="code" class="w-25 bg-white text-dark p-1 rounded" placeholder='{% translate "4 digit code" %}'>
        
        <button type="submit" class="btn btn-primary m-1">verify</button>
        <br>
        {% translate 'please check you spam folder if no email has arrived' %}
    </form>
</div>


<script>
    const nav = document.getElementById('navbar')
    console.log(nav)
    nav.remove()
</script>

{% endblock %}