backend/audio/urls.py
from django.urls import path
from . import views



app_name = 'audio'
urlpatterns = [
    path('', views.dash, name='dash'),
    path('match-audio/<int:level>/<int:lesson>/<int:chunks>', views.match_audio, name='match-audio'),
]

backend/backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext as _
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
   path("admin/", admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += i18n_patterns ( 
    url('', include('homepage.urls', namespace='homepage')),
    url('user-dash', include('user_dash.urls', namespace='user-dash')),
    url('learn/', include('learn.urls', namespace='learn')),
    url('create/', include('create.urls', namespace='create')),
    url('audio/', include('audio.urls', namespace='audio')),
    path("reset-password-sent", auth_views.PasswordResetDoneView.as_view(template_name='password-reset-sent.html'), name='password_reset_done'),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='password-reset-form.html'), name='password_reset_confirm'),
    path("reset-password-complete", auth_views.PasswordResetCompleteView.as_view(template_name='password-reset-complete.html'), name='password_reset_complete'),
    
   

)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

backend/create/urls.py
from django.urls import path
from . import views


app_name = 'create'
urlpatterns = [
    path('dash', views.dash, name='dash'),
    path('lessons/<int:level>', views.lessons, name='lessons'),
    path('lesson/<int:id>/<int:level>', views.lesson, name='lesson'),
    path('alts/<int:id>/<int:level>', views.alts, name='alts'),
    path('alt/<int:id>/<int:lesson_id>/<int:level>', views.alt, name='alt'),
    path('create-edit-level/<int:id>', views.create_edit_level, name='create-edit-level'), 
    path('create-edit-lesson/<int:id>/<int:level>', views.create_edit_lesson, name='create-edit-lesson'), 
    path('missing-words/<int:id>/<int:level>', views.lesson, name='missing-words'), 
    path('add-info/<int:lesson_id>/<int:level>', views.add_info, name='add-info'),
    path('edit-entries/', views.edit_entries, name='edit-entries'),
    path('edit-entry/<int:id>', views.edit_entry, name='edit-entry'),
    path('ajax-search-entry/', views.ajax_search_entry, name="ajax_search_entry"),
    path('ajax-save-entries/', views.ajax_save_entries, name="ajax_save_entries"),
    path('ajax-add-lesson-id/<int:lesson>/<int:level>', views.ajax_add_lesson_id, name="ajax_add_lesson_id"),
    path('ajax-delete-lesson-id/<int:lesson>/<int:level>', views.ajax_delete_lesson_id, name="ajax_delete_lesson_id"),
    path('ajax-set-level-order/<int:level>/<str:order>', views.ajax_set_level_order, name="ajax_set_level_order"),
    path('ajax-autofill-missing-words/', views.ajax_autofill_missing_words, name="ajax_autofill_missing_words"),
    # ajax call probably needs reghex to get url and append ajax-search-entry, working in lesson, but not alt
]

backend/homepage/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'homepage'
urlpatterns = [
    path("", views.homepage, name='homepage'),
    path("login", views.login_form, name='login'),
    path('logout', views.logout_form, name='logout'),
    path("signup", views.signup_form, name='signup'),
    path("signup", views.signup_form, name='signup'),
    path("verify-email", views.verify_email, name='verify-email'),
    path("podcast", views.podcast, name='podcast'),
    path("sample", views.sample, name='sample'),
    path("reset-password", auth_views.PasswordResetView.as_view(template_name='reset-password.html'), name='reset_password'),
    

]

backend/create/forms.py
from django.forms import ModelForm, Textarea, TextInput
from .models import Lesson, Level, Entry


class LessonForm(ModelForm):
   
   class Meta:
      model = Lesson
      widgets = {
               'description': Textarea(attrs={'cols': 30, 'rows': 10}),
               'slo_description': Textarea(attrs={'cols': 30, 'rows': 10}),

         }
      exclude = ('entries', 'missing_words', 'date','slo_date', 'image')
   def __init__(self, *args, **kwargs):
            super(LessonForm, self).__init__(*args, **kwargs)
            self.fields['title'].widget = TextInput(attrs={'class': 'form-control', 'placeholder': 'title'})
            self.fields['slo_title'].widget = TextInput(attrs={'class': 'form-control', 'placeholder': 'slo title'})
            self.fields['description'].widget = TextInput(attrs={'class': 'form-control', 'placeholder': 'description'})
            self.fields['slo_description'].widget = TextInput(attrs={'class': 'form-control', 'placeholder': 'slo description'})
            self.fields['level'].widget = TextInput(attrs={'id': 'level-field'})
            for fieldname in ['title','slo_title', 'description', 'slo_description']:
               self.fields[fieldname].label = ''


class LevelForm(ModelForm):
   
   class Meta:
      model = Level
      exclude = ('order',)

class EntryForm(ModelForm):
   
   class Meta:
      model = Entry
      fields = ('eng', 'slo')
   def __init__(self, *args, **kwargs):
      super(EntryForm, self).__init__(*args, **kwargs)
      self.fields['eng'].widget = TextInput(attrs={'class': 'form-control m-4', 'placeholder': 'eng'})
      self.fields['slo'].widget = TextInput(attrs={'class': 'form-control m-4', 'placeholder': 'slo'})
      for fieldname in ['eng', 'slo']:
         self.fields[fieldname].label = ''

backend/homepage/forms.py
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import UserProfile
from django import forms
from django.forms import CharField, EmailField, EmailInput, ModelChoiceField, PasswordInput, TextInput
from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate, gettext


class NewUserForm(UserCreationForm):
    
    class Meta:
        model = get_user_model()
        fields = ['email', 'username']
        
    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = EmailInput(attrs={'class': 'form-control', 'placeholder':  _('email')})
        self.fields['username'].widget = TextInput(attrs={'class': 'form-control', 'placeholder':  _('username')})
        self.fields['password1'].widget = PasswordInput(attrs={'class': 'form-control', 'placeholder':  _('password')})
        self.fields['password2'].widget = PasswordInput(attrs={'class': 'form-control', 'placeholder':  _('repeat password')})
        for fieldname in ['email','username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].label = ''

class UserAuthenticationForm(AuthenticationForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget = TextInput(attrs={'class': 'form-control', 'placeholder':  _('email')})
        self.fields['password'].widget = PasswordInput(attrs={'class': 'form-control', 'placeholder': _('password')})
        for fieldname in ['username','password']:
            self.fields[fieldname].label = ''
            


    def confirm_login_allowed(self, user):
        
        if not user.is_active or not user.is_validated:
            raise forms.ValidationError('There was a problem with your login.', code='invalid_login')

backend/create/views.py
from shutil import move 
from turtle import update
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from .models import Lesson, Entry, Level
from .forms import LessonForm, LevelForm, EntryForm
from audio.models import AudioClip
import ast
import os
from django.http import JsonResponse
from django.urls import resolve
from django.views.decorators.csrf import csrf_exempt
import random
#from .verbs_archive import verbs


@user_passes_test(lambda u: u.is_superuser)
def dash(request):
    if request.POST:
        new_lesson = Lesson.objects.create()
        return redirect('create:lesson', new_lesson.id)
    return render(request, 'create/dash.html')


def lessons(request, level):
    try:
        level_obj = Level.objects.get(level=level)
        level_order = level_obj.order
    except:
        level_obj = []
        level_order = []

    if request.POST:
        level_obj.is_live = 'true'
        level_obj.save()
       
    lessons = Lesson.objects.values().filter(level=level)
    all_lessons = {}

    for lesson in lessons:
        lesson_has_audio = check_audio(lesson)
        
        if lesson_has_audio:
            lesson['has_audio'] = 'true'
        obj = Lesson.get_percentages(lesson)
        lesson['create_progress'] = obj
        all_lessons[str(lesson['id'])] = lesson
    
    
    context = {
        'lessons': all_lessons,
        'levels':  Level.objects.all(),
        'selected_level': level_obj,
        'level_order': level_order
        }

    return render(request, 'create/lessons.html', context)

def check_audio(lesson):
    entries = Entry.objects.filter(id__in=lesson.get('entries'))
    if not entries:
        return False
    for entry in entries:
        if entry.audio != 'true':
            return False
    return True
            

            
def create_edit_level(request, id):
    if request.POST:
        edit = int(request.POST.get('pk'))
        if edit:
            instance = get_object_or_404(Level, level=edit)
            filled_form = LevelForm(
                request.POST, request.FILES, instance=instance)
        else:
            filled_form = LevelForm(request.POST, request.FILES,)
        if filled_form.is_valid():
            filled_form.save()
        return redirect('create:dash')
    if id != 0:
        level = get_object_or_404(Level, id=id)
        form = LevelForm(instance=level)
    else:
        level = ""
        form = LevelForm()

    context = {
        'level': level,
        'form': form,
        'id': id
    }
    return render(request, 'create/create-edit-level.html', context)

def create_edit_lesson(request, id, level):
    level_obj = Level.objects.get(level=level)
    if request.POST:
        edit = int(request.POST.get('pk'))
        if edit:
            instance = get_object_or_404(Lesson, id=edit)
            filled_form = LessonForm(
                request.POST, request.FILES, instance=instance)
        else:
            filled_form = LessonForm(request.POST, request.FILES,)
        if filled_form.is_valid():
            filled_form.save()
        return redirect('create:lessons', level) 
    if id != 0:
        lesson = get_object_or_404(Lesson, id=id)
        form = LessonForm(instance=lesson)
    else:
        lesson = ""
        form = LessonForm()
    context = {
        'lesson': lesson,
        'level': level_obj,
        'form': form,
        'id': id,
    }
    return render(request, 'create/create-edit-lesson.html', context)


def get_words_and_options(request, entries, lang):
    data = {}
    counter = 0
    for entry in entries:
        word = request.POST.get(f'{lang}_word_{counter}')
        options = request.POST.getlist(f'{lang}_option_{counter}')
        data[entry.get('id')] = {'word': word, 'options': options}
        counter += 1
    return data

# lesson handles both create content and missing words
def lesson(request, id, level):
    current_url = resolve(request.path_info).url_name
    base_url = str(os.getenv('BASE_URL'))
    lesson, entries, ids = Lesson.get_entries_in_order(id)
    if request.POST:
        eng_data = get_words_and_options(request, entries, 'eng')
        slo_data = get_words_and_options(request, entries, 'slo')
        lesson_obj = Lesson.objects.get(id=id)
        lesson_obj.missing_words = {
            "eng_data": eng_data,
            "slo_data": slo_data
        }
        lesson_obj.save()
        return redirect('create:lessons', level)
    if entries:
        context = {
            'lesson': lesson,
            'entries': entries,
            'lesson_id': id,
            'ids': ids,
            'level': level,
            'base_url': base_url
        }
    else:
        context = {
            'lesson': lesson,
            'lesson_id': id,
            'level': level,
            'base_url': base_url
        }
 
    if current_url == 'missing-words':
        page = 'create/missing-words.html'
        eng_words = []
        slo_words = []
        
        for entry in entries:
            split_engs = entry['eng'].split(' ')
            split_slos = entry['slo'].split(' ')
            # removes commas and others from dialoge texts
            for i in range(len(split_engs)):
                for char in split_engs[i]:
                    if char in '.,:;?!\'"()[]{}<>\/|`~@#$%^&*-_=+':
                        split_engs[i] = split_engs[i].replace(char, '')
                        split_slos[i] = split_slos[i].replace(char, '')
            
            eng_words.append(split_engs)
            slo_words.append(split_slos)
            
        counter = 0
        for entry in entries:
            entry['eng_words'] = eng_words[counter]
            entry['slo_words'] = slo_words[counter]
            counter += 1
        
    else:
        page = 'create/content.html'

    return render(request, page, context)


def alts(request, id, level):
    lesson, entries, ids = Lesson.get_entries_in_order(id)
    context = {
        'entries': entries,
        'lesson': lesson,
        'level': level,
        'lesson_id_as_string' : str(lesson.get('id'))   
    }
    return render(request, 'create/alts.html', context)


def alt(request, id, lesson_id, level):
    base_url = str(os.getenv('BASE_URL'))
    lesson = Lesson.objects.values().filter(pk=lesson_id)
    entry = Entry.objects.get(pk=id)
    
    try: alt_ids = entry.alts[str(lesson_id)]
    except: alt_ids = []
    alts = []
    for alt_id in alt_ids:
        altEntries = Entry.objects.values().filter(pk=alt_id)
        alts.append(altEntries[0])
    context = {
        # need be .values so that JSON can be read in react on the frontend
        'lesson': lesson[0],
        'entry': Entry.objects.filter(pk=id).values()[0],
        'alts': alts,
        'level': level,
        'base_url': base_url
    }

    return render(request, 'create/alt-content.html', context)


def add_info(request, lesson_id, level):
    lesson = Lesson.objects.get(id=lesson_id)
    entries = Entry.objects.filter(id__in=lesson.entries)
    if request.POST:
        in_slo = request.POST.getlist('text-in-slo')
        in_eng = request.POST.getlist('text-in-eng')
        
        #ids = request.POST.getlist('id')
        #infos = []
        counter = 0
        for entry in entries:
            obj = {'lesson': lesson_id, 'slo': in_eng[counter], 'eng': in_slo[counter]}
            entry.info[level] = obj
            entry.save()
            counter += 1
        return redirect('create:add-info', lesson_id, level)
    context = {
        'entries': entries,
        'lesson': lesson,
        'level': level,
    }
    return render(request, 'create/add-info.html', context)

def edit_entries(request):
    context = {
        'base_url': str(os.getenv('BASE_URL'))
    }
    return render(request, 'create/edit-entries.html', context)

def edit_entry(request, id):
    instance = get_object_or_404(Entry, pk=id)
    lessons = Lesson.objects.all()
    appears_in = []
    for lesson in lessons:
        if id in lesson.entries:
            obj = {'level': lesson.level, 'title': lesson.title}
            appears_in.append(obj)
            
    if request.POST:
        replacement = request.POST.get('replacement')
        if replacement:
            eng_rep = request.FILES.get('eng')
            slo_rep = request.FILES.get('slo')
            try:
                eng_rep.name = instance.eng_audio
            except:
                pass
            try:
                slo_rep.name = instance.slo_audio
            except:
                pass
            if eng_rep and slo_rep:
                eng_audio = AudioClip.objects.get(file=f'clips/{instance.eng_audio}')
                slo_audio = AudioClip.objects.get(file=f'clips/{instance.slo_audio}')
                eng_audio.file = eng_rep
                slo_audio.file = slo_rep
                eng_audio.save()
                slo_audio.save()
            elif eng_rep:
                eng_audio = AudioClip.objects.get(file=f'clips/{instance.eng_audio}')
                eng_audio.file = eng_rep
                eng_audio.save()
            else:
                slo_audio = AudioClip.objects.get(file=f'clips/{instance.slo_audio}')
                slo_audio.file = slo_rep
                slo_audio.save()
            return redirect('create:edit-entry', id)    
        else:
            form = EntryForm(request.POST, instance=instance)
            form.save()
            return redirect('create:edit-entry', id)
    context = {
        'form': EntryForm(instance=instance),
        'entry': instance,
        'appears_in': appears_in,
        'eng_url': str(os.getenv('AWS_CLIPS_BASE_URL')) + instance.eng_audio,
        'slo_url': str(os.getenv('AWS_CLIPS_BASE_URL')) + instance.slo_audio,
    }
    return render(request, 'create/edit-entry.html', context)

def ajax_search_entry(request):
    obj = decodeJavaScript(request)
    query = obj.get('query')
    single_word = obj.get('single')

backend/homepage/templates/create/dash.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<link rel="stylesheet" href="{% static 'styles/create/styles.css' %}" />
<!--link rel="stylesheet" media="screen and (max-width: 1050px)" href="{% static 'styles/homepage/mobile.css' %}"/> <span><p>{% translate "hello" %}</p></span> -->
{% endblock %}
<h3 class="page-header">create</h3>


<a href="{% url 'create:lessons' 1 %}" class="btn btn-primary">lessons</a>
<a href="{% url 'audio:dash' %}" class="btn btn-primary">audio</a>
<a href="{% url 'create:edit-entries' %}" class="btn btn-primary">edit entry</a>



{% endblock %}

backend/homepage/templates/create/lessons.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<link rel="stylesheet" href="{% static 'styles/create/lessons.css' %}" />
<!--link rel="stylesheet" media="screen and (max-width: 1050px)" href="{% static 'styles/homepage/mobile.css' %}"/> <span><p>{% translate "hello" %}</p></span> -->
{% endblock %}
<h3 class="page-header">create</h3>

<div class="m-2">
    <a href="{% url 'create:create-edit-level' 0 %}" class="btn btn-primary">create new level</a>
    <a href="{% url 'create:create-edit-lesson' 0 selected_level.level %}" class="btn btn-primary">create new lesson</a>
    <a class="btn btn-secondary" href="{% url 'create:create-edit-level' selected_level.level %}" >edit level {{ selected_level.level }}</a>
    <select id="level-select" value="{{ selected_level.level }}">
        <option hidden>select level</option>
        {% for level in levels %}
        <option {% if level.level == selected_level.level %} selected {% endif %} class="{{ level.level }}" 
        value="{% url 'create:lessons' level.level %}">{{ level.level }}. {{ level.title }}</option>
        {% endfor %}
    </select>
</div>
{% if not lessons %}
<h4>{% if selected_level.level == 0 %}
    currently no lessons without a level
    {% else %}
    no lessons in level {{ selected_level.level }}
    {% endif %}
     </h4>
{% else %}
<div class="d-flex justify-content-between">
    <div>
        <h4>lesson order</h4>
        
        
        <ol id="order-list" class="d-flex flex-column dropzone border border-info rounded border-3">
            
        </ol>
    </div>

    <div class="lessons-list-wrapper">
        <h4> level {{ selected_level.level }} </h4>
            <span>{{ selected_level.title }}</span>
        <ol >
            
            {% for k, lesson in lessons.items %}
            <li class="border border-light rounded p-2 m-4" id="{{ lesson.id }}">
                <span class=" m-1 {% if lesson.has_audio == 'true' %}
                text-success
                {% else %}
                text-danger
                {% endif %}"><i class="fa-solid fa-volume-high"></i></span>
                <a class="text-decoration-none" href="{% url 'create:add-info' lesson.id selected_level.level %}">&#9432;</a>
                {% if not lesson.entries %}
                <a class="border border-danger rounded p-1 m-2" href="{% url 'create:lesson' lesson.id selected_level.level  %}">{{ lesson.title }}</a>
                {% else %}
                <a  class="border border-success rounded p-1 m-2" href="{% url 'create:lesson' lesson.id selected_level.level  %}">{{ lesson.title }}</a>
                {% endif %}
                
                {% if lesson.create_progress.alts.0 == lesson.create_progress.alts.1 and lesson.create_progress.alts.1 is not 0  %}
                <span class="border border-success rounded p-1 m-2">
                    <a  href="{% url 'create:alts' lesson.id selected_level.level  %}">alternates</a>
                    <span>{{ lesson.create_progress.alts.0 }}/{{ lesson.create_progress.alts.1 }}</span>
                </span>
                {% else %}
                <span class="border border-danger rounded p-1 m-2">
                    <a  href="{% url 'create:alts' lesson.id selected_level.level %}">alternates</a>
                    <span>{{ lesson.create_progress.alts.0 }}/{{ lesson.create_progress.alts.1 }}</span>
                </span>
                {% endif %}
                
                {% if lesson.create_progress.missing_words.0 == lesson.create_progress.missing_words.1 and lesson.create_progress.missing_words.1 is not 0  %}
                <span class="border border-success rounded p-1 m-2">
                    <a href="{% url 'create:missing-words' lesson.id selected_level.level  %}">missing words</a>
                    <span>{{ lesson.create_progress.missing_words.0 }}/{{ lesson.create_progress.missing_words.1 }}</span>
                </span>
                {% else %}
                <span class="border border-danger rounded p-1 m-2">
                    <a href="{% url 'create:missing-words' lesson.id selected_level.level  %}">missing words</a>
                    <span>{{ lesson.create_progress.missing_words.0 }}/{{ lesson.create_progress.missing_words.1 }}</span>
                </span>
                {% endif %}
             
                
                <a class="btn btn-secondary" href="{% url 'create:create-edit-lesson' lesson.id selected_level.level %}">edit</a>
                <span class="m-2">
                    <button class="btn btn-success" name="add-button" onclick="backendAdd(this)" value="{{ lesson.id }}" 
                     {% if lesson.id in level_order or lesson.create_progress.missing_words.0 != lesson.create_progress.missing_words.1 and lesson.create_progress.missing_words.1 is not 0 %}
                        disabled 
                     {% endif %}
                     {% if not lesson.has_audio == 'true' %}
                        disabled
                     {% endif %} >+</button>
                    
                </span>
            </li>
            {% endfor %}
            
        </ol>
    </div>
   
</div>
{% endif %}
{% if selected_level.is_live == 'true' %}
<h5 class="border border-success border-3 rounded bg-success text-dark">*****level {{ selected_level.level }} is live, only edit alternates******</h5>
{% else %}
<form id="go-live-form" method="POST">
    {% csrf_token %}
    <span>level {{ selected_level.level }}<input class="m-1" type="checkbox" name="go-live" onchange="toggleGoLive(this)"></span>
    <input type="hidden" name="level" value="{{ selected_level.level }}">
    <br>
</form>
<button id="go-live-button" class="btn btn-danger" onclick="doubleCheck()" disabled>go live</button>
{% endif %}


<input type="hidden" value="{{ csrf_token }}" id="csrf-token" >
{{ level_order|safe | json_script:'levelOrder' }}
{{ lessons|safe | json_script:'lessons' }}

<script>
    function toggleGoLive(e){
        const goLiveButton = document.getElementById('go-live-button')
        if(e.checked){
            goLiveButton.disabled = false
        } else {
            goLiveButton.disabled = true
        }
    }
    function doubleCheck(){
        if (confirm('are you 100% positive the level is ready to go live?')) {
            form = document.getElementById('go-live-form')
            form.submit()
            } else {
            return false
            }
    }

    function ajaxPost(arr){
        const csrfToken = document.getElementById('csrf-token').value
        const select = document.getElementById('level-select')
        const level = select.options[select.selectedIndex].classList
        $.ajax({
            url: '/create/ajax-set-level-order/' + level ,
            method: 'POST',
            credentials: 'same-origin',
            headers:{
                'Accept': 'application/json',
                'X-Requested-With': 'XMLHttpRequest', //Necessary to work with request.is_ajax()
                'X-CSRFToken': csrfToken,
            },
         body: JSON.stringify(arr)
})
        
    }
    function extract(id){
        let context = document.getElementById(id).textContent
        //console.log(context)
        context = context.replace(/'/g, '"')
        
        context = context.slice(1,-1)
        //console.log(context)
        try {
          context = JSON.parse(context) 
          return context 
        } catch (error) {
          console.log(id)
          console.log(error)
          
        }
        
        return context
    }

    function createElem(type, textContent){
        const elm = document.createElement(type)
        elm.innerHTML = textContent
        return elm
    }

    function backendAdd(button){
        const id = button.value
        const select = document.getElementById('level-select')
        const level = select.options[select.selectedIndex].classList
        $.ajax({
            url: '/create/ajax-add-lesson-id/' + id + '/' + level,
            dataType: 'json',
            success: function(data) {
                levelOrder = data
                populateLevelOrder(data)
    }})
     button.disabled = true
        
    }


    function backendDelete(id){
        const select = document.getElementById('level-select')
        const level = select.options[select.selectedIndex].classList
        $.ajax({
            url: '/create/ajax-delete-lesson-id/' + id + '/' + level,
            dataType: 'json',
            success: function(data) {
                levelOrder = data
                populateLevelOrder(data)
                enableButton(id)
    }})
        
    }

    function enableButton(id){
        const buttons = document.getElementsByName('add-button')
        buttons.forEach(button => {
            if (id === button.value){
                button.disabled = false
                return false
            }
        })
    }

    

    function populateLevelOrder(levelOrder){
        orderList.innerHTML = ''
        levelOrder.forEach(id => {
            const li = createElem('li', null)
            const span = createElem('span', lessons[id].title)
            const button = createElem('button', 'X')
            button.value = id
            button.setAttribute('onclick','backendDelete(this.value)')
            button.classList.add('btn','btn-danger','m-1', 'btn-sm')
            li.append(span, button)
            li.draggable = true
            li.classList.add('border','border-dark', 'rounded','p-1', 'm-2')
            li.id = id
            orderList.append(li)
        })
        
    }

  

    let levelOrder = extract('levelOrder')
    const lessons = extract('lessons')
    let orderList  = document.getElementById('order-list')
    if (!orderList) {
        orderList = []
    }
    populateLevelOrder(levelOrder)
    
    
    
   

    let draggedId = null
    let draggedIndex = null
        
    document.addEventListener("dragstart", (event) => {
    draggedId = parseInt(event.target.id)
    draggedIndex = levelOrder.indexOf(draggedId)
    });

    document.addEventListener("dragover", (event) => {
    // prevent default to allow drop
    event.preventDefault();
    let draggedOverId = parseInt(event.target.id)
    if (levelOrder.includes(draggedOverId)){
        const li = document.getElementById(draggedOverId)
        li.classList.add('bg-warning')
    }
    
    });

    document.addEventListener("dragleave", (event) => {
        event.preventDefault();
    let draggedOverId = parseInt(event.target.id)
    if (levelOrder.includes(draggedOverId)){
        const li = document.getElementById(draggedOverId)
        li.classList.remove('bg-warning')
    }
});

    document.addEventListener("drop", (event) => {
    // prevent default action (open as link for some elements)
    event.preventDefault();
    let droppedOnId = parseInt(event.target.id)
    if (levelOrder.includes(droppedOnId)){
        levelOrder.splice(draggedIndex, 1)
        const droppedOnIndex = levelOrder.indexOf(droppedOnId)
        levelOrder.splice(droppedOnIndex , 0, draggedId )
        
        const select = document.getElementById('level-select')
        const level = select.options[select.selectedIndex].classList
        const levelOrderAsStr = JSON.stringify(levelOrder)
        $.ajax({
            url: '/create/ajax-set-level-order/' + level + '/' +  levelOrderAsStr,
            dataType: 'json',
            success: function(data) {
                populateLevelOrder(levelOrder)
    }})
    }
    });


    document.getElementById('level-select').onchange = function() {
    if (this.selectedIndex!==0) {
        window.location.href = this.value
    }        
    };


</script>

{% endblock %}