backend/audio/urls.py
from django.urls import path
from . import views



app_name = 'audio'
urlpatterns = [
    path('', views.dash, name='dash'),
    path('match-audio/<int:level>/<int:lesson>/<int:chunks>', views.match_audio, name='match-audio'),
]

backend/backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext as _
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
   path("admin/", admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += i18n_patterns ( 
    url('', include('homepage.urls', namespace='homepage')),
    url('user-dash', include('user_dash.urls', namespace='user-dash')),
    url('learn/', include('learn.urls', namespace='learn')),
    url('create/', include('create.urls', namespace='create')),
    url('audio/', include('audio.urls', namespace='audio')),
    path("reset-password-sent", auth_views.PasswordResetDoneView.as_view(template_name='password-reset-sent.html'), name='password_reset_done'),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='password-reset-form.html'), name='password_reset_confirm'),
    path("reset-password-complete", auth_views.PasswordResetCompleteView.as_view(template_name='password-reset-complete.html'), name='password_reset_complete'),
    
   

)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

backend/homepage/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'homepage'
urlpatterns = [
    path("", views.homepage, name='homepage'),
    path("login", views.login_form, name='login'),
    path('logout', views.logout_form, name='logout'),
    path("signup", views.signup_form, name='signup'),
    path("signup", views.signup_form, name='signup'),
    path("verify-email", views.verify_email, name='verify-email'),
    path("podcast", views.podcast, name='podcast'),
    path("sample", views.sample, name='sample'),
    path("reset-password", auth_views.PasswordResetView.as_view(template_name='reset-password.html'), name='reset_password'),
    

]

backend/learn/urls.py
from django.urls import path
from . import views


app_name = 'learn'
urlpatterns = [
    path('dash', views.dash, name='dash'),
    path('my-account/', views.my_account, name='my-account'),
    path('select-lesson/<int:level>', views.select_lesson, name='select-lesson'),
    path('lesson/<int:level>/<int:id>', views.lesson, name='lesson'),
    path('add-remove-homework/', views.add_remove_homework, name='add-remove-homework'),
    path('homework/', views.homework, name='homework'),
    path("check-username-exists/", views.ajax_check_username_exists, name='check-username-exists'),
    path('adjust-progress/', views.adjust_progress, name='adjust-progress'),
    path('no-cheating/', views.no_cheating, name='no-cheating'),
    

] 

backend/homepage/views.py
from django.shortcuts import render, redirect
from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate, gettext
from .models import UserProfile
from .forms import NewUserForm, UserAuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.core.exceptions import ValidationError
from random import randrange
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
import os


def homepage(request):
    if request.user.is_authenticated:
        return redirect('learn:dash')
    #trans = translate(language='en')
    return render(request, 'homepage.html')

def sample(request):
    return render(request, 'sample.html')


def verify_email(request):
    msg = ''
    if request.POST:
        user_code = request.POST.get('code')
        user_model = UserProfile.objects.get(email=request.user)

        if user_code == str(user_model.verification_code):
            user_model.is_verified = True
            user_model.verification_code = 0
            user_model.save()
            return redirect('homepage:homepage')
        else:
            msg = 'incorrect code'
    context = {'msg': msg}
    return render(request, 'verify-email.html', context)


def login_form(request):
    if request.user.is_authenticated:
        return redirect('learn:dash')
    if request.method == 'GET':
        return render(request, 'login.html', {'form': UserAuthenticationForm()})
    else:
        user = authenticate(
            request, email=request.POST['username'], password=request.POST['password'])

        if user is None:
            return render(request, 'login.html', {'form': UserAuthenticationForm(), 'error': 'username or password incorrect'})
        else:
            login(request, user)
            if request.user.is_superuser:
                return redirect('homepage:homepage')
            else:
                return redirect('learn:dash')


def logout_form(request):
    if request.method == "POST":
        logout(request)
        return redirect('homepage:homepage')


def signup_form(request):
    if request.user.is_authenticated:
        return redirect('user_dash:index')
    if request.method == 'GET':
        return render(request, 'signup.html', {'form': NewUserForm()})
    else:
        # check if email is in focus group -------------------
        focus_string = str(os.getenv('FOCUS_GROUP'))
        focus_group = [x.strip() for x in focus_string.split(',')]
        if request.POST['email'] not in focus_group:
            msg = 'focus-group-error'
            return render(request, 'signup.html', {'form': NewUserForm(), 'error': msg})
        # end check ------------------------
        if request.POST['password1'] == request.POST['password2']:
            try:
                four_digit_code = randrange(1000, 9999)
                language_code = request.POST.get('language-code')
                user = UserProfile.objects.create_user(
                    request.POST['email'], request.POST['username'], password=request.POST['password1'])
                user.verification_code = four_digit_code
                user.website_lang = language_code
                user.save()

                subject = 'Verification Code'
                html_message = render_to_string(
                    'verification-mail-template.html', {'user': user.username, 'code': four_digit_code})
                plain_message = strip_tags(html_message)
                from_email = 'slolearner.net <contact@slolearner.net>'
                to = request.POST['email']
                mail.send_mail(subject, plain_message, from_email, [
                               to], html_message=html_message)
                login(request, user)
 
                return redirect('homepage:verify-email')
            except IntegrityError:
                ValidationError("User with this email already exist")
                return render(request, 'customer/auth/signup.html', {'form': NewUserForm(), 'error': 'account already exists under this email'})

        else:
            return render(request, 'customer/auth/signup.html', {'form': NewUserForm(), 'error': 'passwords did not match'})


def podcast(request):
    return render(request, 'podcast.html')


def translate(language, string):
    cur_language = get_language()
    try:
        activate(language)
        text = gettext(string)
    finally:
        activate(cur_language)
    return text

backend/learn/views.py
from re import M
from django.shortcuts import redirect, render, get_object_or_404
from create.models import Lesson, Entry, Level
from homepage.models import UserProfile
from audio.models import AudioClip
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import ast
import logging
import boto3
from botocore.exceptions import ClientError
import os
from django.core.paginator import Paginator
from dotenv import load_dotenv
load_dotenv()

def dash(request):
    if request.POST:
        language = request.POST.get('learning')
        current_user_obj = UserProfile.objects.get(id=request.user.id)
        current_user_obj.first_lang = language
        current_user_obj.save()
        return redirect('learn:dash')
    user = UserProfile.objects.get(email=request.user)
    if user.verification_code != 0:
        return redirect('homepage:verify-email')
    #last 5 entries, if needed. 
    #entries = get_most_recent_homework_entries(user)
    entries = Entry.objects.filter(id__in=user.homework_list)
    if user.is_staff:
        levels = Level.objects.all()
    else:
        levels = Level.objects.filter(is_live='true')
    max_level = user.progress - 1
    try:
        percent_completed = max_level  / len(levels) * 100
    except:
        percent_completed = 0
    context = {
        'entries': len(entries),
        'total_levels': len(levels) + 1,
        'last_avail_level': len(levels),
        'percent_complete': int(percent_completed)
    }
    return render(request, 'learn/dash.html', context)

def my_account(request):
    user = UserProfile.objects.get(email=request.user)
    if request.POST:
        new_username = request.POST.get('username')
        website_lang = request.POST.get('website_lang')
        first_lang = request.POST.get('first_lang')
        if new_username:
            user.username = new_username
        user.website_lang = website_lang
        user.first_lang = first_lang
        user.save()
        #request.path_info = 'sl/'
    context = {
        'user': user,
        'base_url': str(os.getenv('BASE_URL')),
        'required_url': '/' + user.website_lang + '/learn/my-account/'
    }
    return render(request, 'learn/my-account.html', context)

def no_cheating(request):
    return render(request, 'no-cheating.html')

def select_lesson(request, level):
    user = UserProfile.objects.get(email=request.user)
    types_translations = {'dialogue': 'dialog','news':'novice','verb':'glagolnik','keywords':'ključne besede'}
    if level > user.progress:
        return render(request, 'learn/no-cheating.html')
    try:
        results = user.results[str(level)]
    except:
        results = {}
    level_obj = Level.objects.get(level=level)
    lessons = Lesson.objects.filter(id__in=level_obj.order)
    lessons_in_order = []
    for id in level_obj.order:
        for lesson in lessons:
            if lesson.id == id:
                lessons_in_order.append(lesson)
    
    available = []
    
    if not results:
        available.append(lessons_in_order[0].id)
    else:
        for k, v in results.items():
            if v[0] == v[1]:
                available.append(int(k))
        if len(available) < len(lessons_in_order):
            available.append(lessons_in_order[len(available)].id)
    if user.website_lang == 'sl':
        for lesson in lessons:
            lesson.type = types_translations[lesson.type]
    if user.is_staff:
        levels = Level.objects.all()
    else:
        levels = Level.objects.filter(is_live='true')
    context = {
        'lessons': lessons_in_order,
        'levels':  levels,
        'level': level_obj,
        'results': results,
        'user': user,
        'available': available
    }
    return render(request, "learn/select-lesson.html", context)



def create_presigned_url(bucket_name, object_name, expiration=3600):
    # Generate a presigned URL for the S3 object
    s3_client = boto3.client('s3')
    try:
        response = s3_client.generate_presigned_url('get_object',
                                                    Params={'Bucket': bucket_name,
                                                            'Key': object_name},
                                                    ExpiresIn=expiration)
    except ClientError as e:
        logging.error(e)
        return None

    # The response contains the presigned URL
    return response

def lesson(request, level, id):
    level_obj = Level.objects.get(level=level)
    user = UserProfile.objects.get(email=request.user)
    
    homework_list = user.homework_list
    if id == 0: # 0 means homework
        lesson = 'homework'
        entries = Entry.objects.filter(id__in=homework_list).values()
    else:
        lesson = Lesson.objects.filter(id=id).values()
        entries = Entry.objects.filter(id__in=lesson[0].get('entries')).values()
    entries_arr = Entry.get_alts_data(entries, id)
    #audio = create_presigned_url('slolearner-audio-files', '1-eng.mp3', expiration=3600)
    #print(audio)
    
    # needed as django loves to place the entries in numerical order of their ID's, this also appears in Create.models called "get_entries_in_order"
    ordered_entries = []
    for id in lesson[0]['entries']:
        for entry in entries_arr:
            if id == entry['id']:
                ordered_entries.append(entry)


    context = {
        'format': lesson[0].get('type'),
        # lesson needs to be as a string (for JS) and object (for img)
        #'lesson_obj':Lesson.objects.get(id=id),
        'lesson': lesson[0],
        'entries': ordered_entries,
        'homework': homework_list,
        'level': level,
        'lessons_in_order': level_obj.order,
        'base_url': str(os.getenv('BASE_URL')),
        'aws_clips_base_url': str(os.getenv('AWS_CLIPS_BASE_URL'))
    }
    
    return render(request, "learn/lesson.html", context)

def homework(request):
    user = UserProfile.objects.get(email=request.user)
    if request.POST:
        items_per_page = request.POST.get('items-per-page')
        items_per_page = int(items_per_page)
        side = request.POST.get('side')
        if side:
            hw_first_lang = request.POST.get('first-lang')
            if side == 'shuffle':
                hw_first_lang = 'shuffle'
            else:
                if hw_first_lang == 'eng':
                    hw_first_lang = 'slo'
                else:
                    hw_first_lang = 'eng'
            user.hw_first_lang = hw_first_lang
            user.save()
        else:
            hw_first_lang = user.hw_first_lang
    else: 
        hw_first_lang = user.hw_first_lang
        items_per_page = 4
    if hw_first_lang == 'shuffle':
        shuffle = True
    else: shuffle = False
    homework_list = user.homework_list
    queryset = Entry.objects.values().filter(id__in=homework_list)
    paginator = Paginator(queryset, items_per_page)
    
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    base_s3_url = 'https://slolearner-audio-files.s3.eu-central-1.amazonaws.com/clips/'
    audio = AudioClip.objects.all()
    # add full url to entry obj
    for entry in page_obj:
        if type(entry) == dict:
            eng_url = base_s3_url + entry.get('eng_audio')
            slo_url = base_s3_url + entry.get('slo_audio')
            entry['eng_audio'] = eng_url
            entry['slo_audio'] = slo_url
    context = {
        'user': user,
        'page_obj': page_obj,
        'first_lang': hw_first_lang,
        'page_options': [4, 8, 16, 24, len(queryset)],
        'items_per_page': items_per_page,
        'value': [0,1],
        'shuffle': shuffle,
        'base_url': str(os.getenv('BASE_URL')),
        'base_s3_url': base_s3_url,
        'audio': audio
    }
    return render(request, 'learn/homework.html', context)

@csrf_exempt
def add_remove_homework(request):
    user = UserProfile.objects.get(email=request.user)
    homework_list = user.homework_list
    obj = decodeJavaScript(request)
    id = int(obj.get('id'))
    
    if id in homework_list:
        homework_list.remove(id)
        user.homework_list = homework_list
        user.save()
    else:
        homework_list.append(id)
        user.homework_list = homework_list
        user.save()
    updated_user = UserProfile.objects.get(email=request.user)
    homework = updated_user.homework_list
    return JsonResponse(homework,safe=False)

@csrf_exempt
def adjust_progress(request):
    obj = decodeJavaScript(request)
    level = obj.get('level')
    lesson_id = obj.get('lesson_id')
    score = obj.get('score')
    lesson_len = obj.get('lesson_len')
    level_up, max_level = UserProfile.adjust_user_results(request,level, lesson_id, score, lesson_len)
    if level_up:
        next_level = Level.objects.filter(level=max_level).values()
        res = { 'level_up': 'true', 'next_level': next_level[0]}
    else:
        res = { 'level_up': 'false'}
    return JsonResponse(res,safe=False)

def ajax_check_username_exists(request):
    obj = decodeJavaScript(request)
    username_is_taken = UserProfile.objects.filter(username=obj.get('username')).exists()
    if username_is_taken:
        res = 'taken'
    else:
        res = 'available'
    return JsonResponse(res,safe=False)

def decodeJavaScript(request):
    obj_as_string = request.body.decode("utf-8")
    return ast.literal_eval(obj_as_string)

def get_most_recent_homework_entries(user):
    homework_list = user.homework_list
    if homework_list:
        if len(homework_list) < 4 :
            most_recent = homework_list[-5:]
        else:
            most_recent = homework_list[-5:]
    else:
        most_recent = []
    if most_recent:
        return Entry.objects.filter(id__in=most_recent)
    else:
        return []

backend/homepage/templates/learn/dash.html
{% extends "base.html" %} {% block content %}
{% load static %}
{% load i18n %}
{% block css  %}
<link rel="stylesheet" href="{% static 'styles/learn/dash.css' %}" />

{% endblock %}
{% if user.first_lang %}
<h1>
    <span>{% translate "welcome" %}</span>
    <span class="text-info">{{ user.username }}</span>
</h1>
    
<div class="dash-wrapper text-white">
    <div class="progress-box">
        <h5 class="border-top m-1 p-1 border-danger border-3">{% translate "progress" %}</h5>
        <h1 class="border-top m-1 p-1 border-info border-2 text-info">{{ percent_complete }}%</h1>
        <div class="p-4">

        
        <div class="progress m-2">
            
            <div id="progress-bar" class="progress-bar progress-bar-striped bg-info" style="width: 0%" status=True role="progressbar" style='width: 100%' aria-valuemin="0" aria-valuenow="25" aria-valuemax="100"></div>
        </div>
        {% if user.progress == 1 %}
        <a href="{% url 'learn:select-lesson' 1 %}" class="btn btn-primary">{% translate "start learning" %}</a>
        {% else %}

        {% if user.progress == total_levels %}
        <span>{% translate "you are up to date!" %}</span>
        <br>
        <span>{% translate "more levels on the way soon" %}</span>
        <br>
        <a href="{% url 'learn:select-lesson' last_avail_level %}" class="btn btn-primary">{% translate "revise" %} </a>
        {% else %}
        <a href="{% url 'learn:select-lesson' user.progress %}" class="btn btn-primary">{% translate "continue with level" %} {{ user.progress }}</a>
        
        {% endif %}
        
        {% endif %}
        </div>
    </div>
    
   <div class="homework-list">
        <h5 class="border-top m-1 p-1 border-danger border-3">{% translate "homework" %}</h5>
        <h6 class="border-top m-1 p-1 border-info border-2"></h6>
        
        
            {% if not entries %}
            <span>{% translate "add entries to your list using the" %} <span className="homework-add-remove-button unselectable">
                <i class="fa-regular fa-square-plus text-secondary"></i>
            </span>
        </span>
            {% else %}
            <h1 class="text-info">{{ entries }}</h1>
            {% if entries == 1 %}
            <span>{% translate "entry on your list" %}</span>
            {% else %}
            <span>{% translate "entries on your list" %}</span>
            {% endif %}
            <br>
            <a href="{% url 'learn:homework'%}" class="btn btn-primary mt-4">{% translate "study" %}</a>
       
        {% endif %}
    </div>
        
        
<input type="hidden" id="percent-complete" value="{{ percent_complete}}">
</div>
   
        {% else %}
        <h3 class="m-2"><span >pick one </span><span class="text-danger">/</span>/<span class="text-info">/</span> <span> izbrati eno</span></h3>
        <button onclick="submitForm(this.value)" value="eng" class="btn btn-primary m-2">{% translate "I am learning slovenian" %}</button>
        <button onclick="submitForm(this.value)" value="slo" class="btn btn-primary m-2">{% translate "Učim se angleško" %}</button>
        <form method="POST" id="language-form">
            {% csrf_token %}
            <input type="hidden" name="learning" id="language">
        </form>
{% endif %}


<script>
try {
    const percentComplete = document.getElementById('percent-complete')
$("#progress-bar").animate({
    width: percentComplete.value + '%'
}, 2500);
} catch (error) {
    console.log(error)
}

/*

const progressBar = document.getElementById('progress-bar')
progressBar.setAttribute("style", "width: " + percentComplete.value + "%")
*/


    function submitForm(language){
        const input = document.getElementById('language')
        const form = document.getElementById('language-form')
        input.value = language
        form.submit()
        
    }
</script>
{% endblock %}

backend/homepage/templates/learn/lesson.html
{% extends "base.html" %} {% block content %}
{% load static %}
{% load sass_tags %}
{% load i18n %}
{% block css  %}

<link rel="stylesheet" href="{% static 'styles/learn/generator.css' %}" />
<link rel="stylesheet" href="{% static 'styles/learn/line-by-line.css' %}" />

{% endblock %}
<h3 class="page-header">{{ lesson.0.title }}</h3>
<a id="return-button" name="{{ level }}" href="{% url 'learn:select-lesson' level %}"></a>


<input type="hidden" value="{% url 'learn:lesson' level lesson.id %}" id="next-lesson-base-href">
<input type="hidden" value="{{ csrf_token }}" id="csrf-token">
<input type="hidden" value="{{  user.first_lang  }}" id="first-lang">
<input type="hidden" value="{{  user.website_lang  }}" id="website-lang">
<input type="hidden" value="{{ base_url }}" id="base-url">
<input type="hidden" value="{{ aws_clips_base_url }}" id="aws_clips_base_url">

{{ format | json_script:'format' }}
{{ 'false' | json_script:'create' }}
{{ 'false' | json_script:'alts' }}
{{ 'false' | json_script:'altEntry' }}
{{ lesson|safe | json_script:'lesson' }}
{{ lessons_in_order|safe | json_script:'lessons_in_order' }}
{% if not entries %}
{{ "flase"|safe | json_script:'entries' }}
{% else %}
{{ entries|safe | json_script:'entries' }}
{% endif %}
{{ homework|safe | json_script:'homework' }}

{% if format == 'news' %}
<img src="{% static 'images/bg.jpg' %}" id="frontpage-bg" class="d-none">
{% elif format == 'generator' %}
<img src="{% static 'images/eng-flag.png' %}" id="eng-flag" class="d-none">
<img src="{% static 'images/slo-flag.png' %}" id="slo-flag" class="d-none">
{% endif %}
<div id="app">
        
</div>
<script src="{% static 'react-app/build/main.js' %}" ></script>

{% endblock %}

backend/homepage/templates/learn/my-account.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% block css %}
<link rel="stylesheet" href="{% static 'styles/learn/dash.css' %}" /> {% endblock %}
<h1>{% translate "account settings" %}</h1>
<table class="table rounded">
    <form method="POST"> 
    <tbody>
        {% csrf_token %}
        <button id="update-button" type="submit" class="btn btn-primary m-1">update</button>
      <tr>
        <td scope="row">website language <span class="text-danger">/</span>/<span class="text-info">/</span> jezik spletne strani</td>
        <td> 
            <span class="p-2"><input type="radio" name="website_lang" value="en"
                {% if user.website_lang == "en" %}  checked="checked" {% endif %}><img src="{% static 'images/eng-flag.png' %}" class="flag-icon p-1"  ></span>
            <span class="p-2"><input type="radio" name="website_lang" value="sl"
                {% if user.website_lang == "sl" %}  checked="checked" {% endif %}><img src="{% static 'images/slo-flag.png' %}" class="flag-icon p-1" ></span>
        </td>
      
      </tr>
      <tr>
        <td scope="row">I am learning <span class="text-danger">/</span>/<span class="text-info">/</span> učim se  </td>
        <td> 
            <span class="p-2"><input type="radio" name="first_lang" value="slo"
                {% if user.first_lang == "slo" %}  checked="checked" {% endif %}><img src="{% static 'images/eng-flag.png' %}" class="flag-icon p-1" ></span>
            <span class="p-2"><input type="radio" name="first_lang" value="eng"
                {% if user.first_lang == "eng" %}  checked="checked" {% endif %}><img src="{% static 'images/slo-flag.png' %}" class="flag-icon p-1" ></span>
            
        </td>
        
      </tr>
      <tr>
        <td scope="row">change username <span class="text-danger">/</span>/<span class="text-info">/</span> spremeni uporabniško ime</td>
        <td> 
            <span class="invisible border border-2 m-1 rounded p-1"><span id="username-span"></span> is <span id="status"></span></span>
            <br>
            <input name="username" id="username-input" type="text" class="form-control m-2" aria-describedby="inputGroup-sizing-default" placeholder="{{ user.username }}">
        </td>
        
      </tr>
    </tbody>
    </form>
  </table>

  <input type="hidden" value="{{ base_url }}" id="base-url">
<input type="hidden" value="{{ csrf_token }}" id="csrf-token">

{% if required_url != request.path %}
<input type="hidden" value="{{ required_url }}" id="redirect">
{% endif %}


 

  <script>
    const baseUrl = document.getElementById('base-url').value
    const redirect = document.getElementById('redirect')
   if (redirect){
    window.location = baseUrl.slice(0,-4) + redirect.value
   }
    
    const status = document.querySelector('#status')
    const usernameSpan = document.querySelector('#username-span')
    const usernameInput = document.querySelector('#username-input')
    const updateButton = document.querySelector('#update-button')

    let timeout = null
    usernameInput.addEventListener('keyup', function (e) {
    updateButton.disabled = true
    clearTimeout(timeout);
    timeout = setTimeout(function () {
        checkUsernameExists(usernameInput.value)
    }, 1000);
    })

 
    function checkUsernameExists(username){
        const baseUrl = document.getElementById('base-url').value
        const csrfToken = document.getElementById('csrf-token').value
        fetch(baseUrl + 'learn/check-username-exists/', {
        method: 'POST',
        credentials: 'same-origin',
        headers:{
            'Accept': 'application/json',
            'X-Requested-With': 'XMLHttpRequest', //Necessary to work with request.is_ajax()
            'X-CSRFToken': csrfToken,
            },
            body: JSON.stringify({'username': username }) //JavaScript object of data to POST
        })
        .then(response => {
        return response.json() //Convert response to JSON
        
    })
    .then(data => {
        status.innerHTML = data
        status.parentElement.classList.remove('invisible')
        usernameSpan.innerHTML = username
    if (username === ''){
        status.parentElement.classList.add('invisible')
    }
    if (data === 'available'){
        status.parentElement.classList.remove('border-danger')
        status.parentElement.classList.add('border-success')
        updateButton.disabled = false
    } else {
        status.parentElement.classList.remove('border-success')
        status.parentElement.classList.add('border-danger')
    }
    })

    }
    
  </script>
{% endblock %}

backend/homepage/templates/learn/select-lesson.html
{% extends "base.html" %} {% block content %} {% load static %} {% load i18n %} {% load custom-tags %} {% block css %}
<link rel="stylesheet" href="{% static 'styles/learn/select-lesson.css' %}" />
{% endblock %}
<h3 class="page-header">
    {% if user.website_lang == 'en' %} 
    <span>level {{ level.level }}</span>
    <span>:</span>
     <span class="text-info p-2">{{ level.title }} </span>
    {% else %}
    <span class="text-danger">raven {{ level.level }}</span>
    <span>:</span>
    <span class="text-info p-2">{{ level.slo_title }} </span>
    {% endif %}  </h3>
<h4>
    <select id="level-select" onchange="handleChange()">
        <option hidden>{% translate "select level" %}</option>
        {% for level in levels %}
        {% if level.level <= user.progress   %}
        <option {% if level.level == level %} selected {% endif %} value="{% url 'learn:select-lesson' level.level %}">{{ level.level }}. 
            {% if user.website_lang == 'en' %} 
            {{ level.title }}
            {% else %}
            {{ level.slo_title }}
            {% endif %}
        </option>
        {% else %}
          
        {% endif %}
        {% endfor %}
    </select>

</h4>
{% if level.is_live == 'false' and not user.is_superuser %}

<h3>{% translate "lesson under construction, comeback later" %}</h3>
{% else %}

<div>
    
    <ul {% if lessons|length < 2 %} class="center-flex" {% endif %} >
        {% for lesson in lessons %}
        {% if lesson.id not in available %} 
        <li class="locked-lesson lesson border border-primary border-5 rounded" title="{% translate 'complete all previous lessons with a prefect score to unlock' %}">
            <h4> <span class="lesson-number">{% translate "lesson" %}  {{ forloop.counter }}</span></h4>
            <div class="type-and-title">
                <span>{{ lesson.type }}</span>
                <br>
                <span class="title text-light p-2"> 
                    {% if user.website_lang == 'en' %} 
                    {{ lesson.title }}
                    {% else %}
                    {{ lesson.slo_title }}
                    {% endif %}
                </span>
            </div>
            <i class="fa-solid fa-lock"></i>
        </li>
        {% else %}
        <a {% if results|attempted:lesson.id %}
        class="lesson border border-5 border-{{ results|get_grade_color:lesson.id  }}"
        {% else %}
        class="lesson border border-5 border-white" 
        {% endif %}
        href="{% url 'learn:lesson' level.level lesson.id %}">
            <h4> <span class="lesson-number">{% translate "lesson" %} {{ forloop.counter }}</span></h4>
            <div class="type-and-title">
                
                <span>{{ lesson.type }}</span>
                <br>
                <span class="title text-light p-2"> 
                    {% if user.website_lang == 'en' %} 
                    {{ lesson.title }}
                    {% else %}
                    {{ lesson.slo_title }}
                    {% endif %}
                </span>
            </div>
             <div>
                  
            </div>
            <div class="a-buttons">
            </div>
            {% if results|attempted:lesson.id %}
            <span class="p-2 fw-bold">{% translate "top score" %}: {{ results|attempted:lesson.id }} </span>
            {% else %}
            <span class="p-2 text-success fw-bold">{% translate "start" %}</span>
            {% endif %}
        </a>
        {% endif %}
       
        {% endfor %}
    </ul>
    {% endif %}
    <form id="hidden-form" method="GET"></form>
</div>

<script>
    function handleChange() {
        const select = document.getElementById('level-select')
        const form = document.getElementById('hidden-form')
        form.action = select.value
        form.submit()    
    }
</script>
{% endblock %}